nohup salmon quant -i ../../hg19_38/GRCh38_latest_rna_salmon_index -l A -1  ./AB-1_1.fq.gz  -2  ./AB-1_2.fq.gz  -p 16 --validateMappings -o   AB-1    &
nohup salmon quant -i ../../hg19_38/GRCh38_latest_rna_salmon_index -l A -1  ./AB-2_1.fq.gz  -2  ./AB-2_2.fq.gz  -p 16 --validateMappings -o   AB-2    &
nohup salmon quant -i ../../hg19_38/GRCh38_latest_rna_salmon_index -l A -1  ./AB-3_1.fq.gz  -2  ./AB-3_2.fq.gz  -p 16 --validateMappings -o   AB-3    &
nohup salmon quant -i ../../hg19_38/GRCh38_latest_rna_salmon_index -l A -1  ./AL-1_1.fq.gz  -2  ./AL-1_2.fq.gz  -p 16 --validateMappings -o   AL-1    &
nohup salmon quant -i ../../hg19_38/GRCh38_latest_rna_salmon_index -l A -1  ./AL-2_1.fq.gz  -2  ./AL-2_2.fq.gz  -p 16 --validateMappings -o   AL-2    &
nohup salmon quant -i ../../hg19_38/GRCh38_latest_rna_salmon_index -l A -1  ./AL-3_1.fq.gz  -2  ./AL-3_2.fq.gz  -p 16 --validateMappings -o   AL-3    &
nohup salmon quant -i ../../hg19_38/GRCh38_latest_rna_salmon_index -l A -1  ./AP-1_1.fq.gz  -2  ./AP-1_2.fq.gz  -p 16 --validateMappings -o   AP-1    &
nohup salmon quant -i ../../hg19_38/GRCh38_latest_rna_salmon_index -l A -1  ./AP-2_1.fq.gz  -2  ./AP-2_2.fq.gz  -p 16 --validateMappings -o   AP-2    &
nohup salmon quant -i ../../hg19_38/GRCh38_latest_rna_salmon_index -l A -1  ./AP-3_1.fq.gz  -2  ./AP-3_2.fq.gz  -p 16 --validateMappings -o   AP-3    &
nohup salmon quant -i ../../hg19_38/GRCh38_latest_rna_salmon_index -l A -1  ./AS-1_1.fq.gz  -2  ./AS-1_2.fq.gz  -p 16 --validateMappings -o   AS-1    &
nohup salmon quant -i ../../hg19_38/GRCh38_latest_rna_salmon_index -l A -1  ./AS-2_1.fq.gz  -2  ./AS-2_2.fq.gz  -p 16 --validateMappings -o   AS-2    &
nohup salmon quant -i ../../hg19_38/GRCh38_latest_rna_salmon_index -l A -1  ./AS-3_1.fq.gz  -2  ./AS-3_2.fq.gz  -p 16 --validateMappings -o   AS-3    &
nohup salmon quant -i ../../hg19_38/GRCh38_latest_rna_salmon_index -l A -1  ./HB-1_1.fq.gz  -2  ./HB-1_2.fq.gz  -p 16 --validateMappings -o   HB-1    &
nohup salmon quant -i ../../hg19_38/GRCh38_latest_rna_salmon_index -l A -1  ./HB-2_1.fq.gz  -2  ./HB-2_2.fq.gz  -p 16 --validateMappings -o   HB-2    &
nohup salmon quant -i ../../hg19_38/GRCh38_latest_rna_salmon_index -l A -1  ./HB-3_1.fq.gz  -2  ./HB-3_2.fq.gz  -p 16 --validateMappings -o   HB-3    &
nohup salmon quant -i ../../hg19_38/GRCh38_latest_rna_salmon_index -l A -1  ./HL-1_1.fq.gz  -2  ./HL-1_2.fq.gz  -p 16 --validateMappings -o   HL-1    &
nohup salmon quant -i ../../hg19_38/GRCh38_latest_rna_salmon_index -l A -1  ./HL-2_1.fq.gz  -2  ./HL-2_2.fq.gz  -p 16 --validateMappings -o   HL-2    &
nohup salmon quant -i ../../hg19_38/GRCh38_latest_rna_salmon_index -l A -1  ./HL-3_1.fq.gz  -2  ./HL-3_2.fq.gz  -p 16 --validateMappings -o   HL-3    &
nohup salmon quant -i ../../hg19_38/GRCh38_latest_rna_salmon_index -l A -1  ./HP-1_1.fq.gz  -2  ./HP-1_2.fq.gz  -p 16 --validateMappings -o   HP-1    &
nohup salmon quant -i ../../hg19_38/GRCh38_latest_rna_salmon_index -l A -1  ./HP-2_1.fq.gz  -2  ./HP-2_2.fq.gz  -p 16 --validateMappings -o   HP-2    &
nohup salmon quant -i ../../hg19_38/GRCh38_latest_rna_salmon_index -l A -1  ./HP-3_1.fq.gz  -2  ./HP-3_2.fq.gz  -p 16 --validateMappings -o   HP-3    &
nohup salmon quant -i ../../hg19_38/GRCh38_latest_rna_salmon_index -l A -1  ./HS-1_1.fq.gz  -2  ./HS-1_2.fq.gz  -p 16 --validateMappings -o   HS-1    &
nohup salmon quant -i ../../hg19_38/GRCh38_latest_rna_salmon_index -l A -1  ./HS-2_1.fq.gz  -2  ./HS-2_2.fq.gz  -p 16 --validateMappings -o   HS-2    &
nohup salmon quant -i ../../hg19_38/GRCh38_latest_rna_salmon_index -l A -1  ./HS-3_1.fq.gz  -2  ./HS-3_2.fq.gz  -p 16 --validateMappings -o   HS-3    &
